name: Bug Report
description: Choose this template if you want to report a bug.
title: "[BUG] <title>"
labels:
- kind/bug
body:
- type: textarea
  attributes:
    label: "Description"
    description: |
      Explain the bug/issue you are facing, and add a screenshot of any visual artefacts.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Screenshot
    description: Please make sure you have a screenshot in the description of the issue above.
    options:
    - label: I have added a screenshot in the description.
      required: true
- type: textarea
  attributes:
    label: "Expected behavior"
  validations:
    required: true
- type: textarea
  attributes:
    label: "Configuration"
    description: |
      Paste the configuration you are using.
    placeholder: |
      ```lua
      require('gruvbox-material').setup({
        -- your options
      })
      ```
  validations:
    required: true
